spring.application.name=apigateway

server.port=9090

spring.cloud.gateway.server.webmvc.routes[0].id=servicio-cliente
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/clientes/**

spring.cloud.gateway.server.webmvc.routes[1].id=servicio-catalogo
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/productos/**

spring.cloud.gateway.server.webmvc.routes[2].id=servicio-pedido
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/pedidos/**

spring.cloud.gateway.server.webmvc.routes[3].id=servicio-pago
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/pagos/**

spring.cloud.gateway.server.webmvc.routes[4].id=servicio-envio
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/envios/**

spring.cloud.gateway.server.webmvc.routes[5].id=servicio-auth
spring.cloud.gateway.server.webmvc.routes[5].uri=http://localhost:8086
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webmvc.routes[6].id=servicio-inventario
spring.cloud.gateway.server.webmvc.routes[6].uri=http://localhost:8087
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/inventario/**

spring.cloud.gateway.server.webmvc.routes[7].id=servicio-devoluciones
spring.cloud.gateway.server.webmvc.routes[7].uri=http://localhost:8088
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/api/devoluciones/**

spring.cloud.gateway.server.webmvc.routes[8].id=servicio-resenas
spring.cloud.gateway.server.webmvc.routes[8].uri=http://localhost:8089
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/api/resenas/**

spring.cloud.gateway.server.webmvc.routes[9].id=servicio-notificaciones
spring.cloud.gateway.server.webmvc.routes[9].uri=http://localhost:8090
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/api/notificaciones/**